INSERT INTO users (login, password, created_at, update_at) VALUES ('test', 'test',current_timestamp, current_timestamp);


INSERT INTO university (name, created_at, update_at) VALUES ('КГПИ',current_timestamp, current_timestamp);
INSERT INTO university (name, created_at, update_at) VALUES ('СИБГИУ', current_timestamp, current_timestamp);
INSERT INTO university (name, created_at, update_at) VALUES ('НГУ', current_timestamp, current_timestamp);
INSERT INTO university (name, created_at, update_at) VALUES ('НТТТ', current_timestamp, current_timestamp);
INSERT INTO university (name, created_at, update_at) VALUES ('РГУ', current_timestamp, current_timestamp);
INSERT INTO university (name, created_at, update_at) VALUES ('МГУ', current_timestamp, current_timestamp);


INSERT INTO groups (name, university_id, created_at, update_at) VALUES ('ИВТ-18', 1, current_timestamp, current_timestamp);
INSERT INTO groups (name, university_id, created_at, update_at) VALUES ('ММ-22', 1, current_timestamp, current_timestamp);
INSERT INTO groups (name, university_id, created_at, update_at) VALUES ('С-182', 2, current_timestamp, current_timestamp);
INSERT INTO groups (name, university_id, created_at, update_at) VALUES ('СТВ-18', 2, current_timestamp, current_timestamp);


INSERT INTO discipline (name, created_at, update_at) VALUES ('Математический анализ', current_timestamp, current_timestamp);
INSERT INTO discipline (name, created_at, update_at) VALUES ('Физика', current_timestamp, current_timestamp);
INSERT INTO discipline (name, created_at, update_at) VALUES ('Информатика и программирование', current_timestamp, current_timestamp);
INSERT INTO discipline (name, created_at, update_at) VALUES ('Дискретная математика', current_timestamp, current_timestamp);
INSERT INTO discipline (name, created_at, update_at) VALUES ('Базы данных', current_timestamp, current_timestamp);
INSERT INTO discipline (name, created_at, update_at) VALUES ('Web программирование', current_timestamp, current_timestamp);
INSERT INTO discipline (name, created_at, update_at) VALUES ('Философия', current_timestamp, current_timestamp);
INSERT INTO discipline (name, created_at, update_at) VALUES ('Венитиляция промышленных зданий', current_timestamp, current_timestamp);
INSERT INTO discipline (name, created_at, update_at) VALUES ('Газоснабжение', current_timestamp, current_timestamp);
INSERT INTO discipline (name, created_at, update_at) VALUES ('Теплоснабжение', current_timestamp, current_timestamp);


INSERT INTO student (first_name, surname, patronymic, birthday, date_admission, group_id, created_at, update_at) VALUES ('Иванов', 'Иван','Иванович', '1997-04-05', '2018-06-05', 1, current_timestamp, current_timestamp);
INSERT INTO student (first_name, surname, patronymic, birthday, date_admission, group_id, created_at, update_at) VALUES ('Петров', 'Петр','Петрович', '1997-03-05', '2018-05-22', 1, current_timestamp, current_timestamp);
INSERT INTO student (first_name, surname, patronymic, birthday, date_admission, group_id, created_at, update_at) VALUES ('Макаров', 'Георгий','Михайлович', '1997-02-05', '2018-09-26', 1, current_timestamp, current_timestamp);
INSERT INTO student (first_name, surname, patronymic, birthday, date_admission, group_id, created_at, update_at) VALUES ('Ильина', 'Варвара','Всеволодовна', '1997-06-08', '2022-01-21', 2, current_timestamp, current_timestamp);
INSERT INTO student (first_name, surname, patronymic, birthday, date_admission, group_id, created_at, update_at) VALUES ('Спиридонов', 'Александр','Елисеевич', '1997-06-21', '2022-05-29', 2, current_timestamp, current_timestamp);
INSERT INTO student (first_name, surname, patronymic, birthday, date_admission, group_id, created_at, update_at) VALUES ('Леонова', 'Милана','Владимировна', '1997-04-05', '2022-06-08', 2, current_timestamp, current_timestamp);
INSERT INTO student (first_name, surname, patronymic, birthday, date_admission, group_id, created_at, update_at) VALUES ('Тихомирова', 'Таисия','Никитична', '1997-08-03', '2018-06-02', 3, current_timestamp, current_timestamp);
INSERT INTO student (first_name, surname, patronymic, birthday, date_admission, group_id, created_at, update_at) VALUES ('Галкин', 'Мирон','Тимурович', '1997-04-16', '2018-07-18', 3, current_timestamp, current_timestamp);
INSERT INTO student (first_name, surname, patronymic, birthday, date_admission, group_id, created_at, update_at) VALUES ('Зайцев', 'Артём','Артурович', '1997-08-03', '2018-06-21', 3, current_timestamp, current_timestamp);
INSERT INTO student (first_name, surname, patronymic, birthday, date_admission, group_id, created_at, update_at) VALUES ('Семенов', 'Михаил','Романович', '1997-09-05', '2020-10-29', 4, current_timestamp, current_timestamp);
INSERT INTO student (first_name, surname, patronymic, birthday, date_admission, group_id, created_at, update_at) VALUES ('Кондрашов', 'Дмитрий','Львович', '1997-12-01', '2020-09-12', 4, current_timestamp, current_timestamp);
INSERT INTO student (first_name, surname, patronymic, birthday, date_admission, group_id, created_at, update_at) VALUES ('Андреев', 'Лев','Иванович', '1997-11-23', '2020-09-26', 4, current_timestamp, current_timestamp);


INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (1, 1, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (1, 1, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (1, 1, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (1, 1, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (1, 1, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (1, 1, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (1, 2, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (1, 2, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (1, 2, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (1, 2, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (1, 2, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (1, 2, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (1, 3, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (1, 3, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (1, 3, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (1, 3, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (1, 3, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (1, 3, 5, current_timestamp, current_timestamp);

INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (2, 1, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (2, 1, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (2, 1, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (2, 1, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (2, 1, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (2, 1, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (2, 4, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (2, 4, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (2, 4, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (2, 4, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (2, 4, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (2, 4, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (2, 4, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (2, 5, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (2, 5, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (2, 5, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (2, 5, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (2, 5, 5, current_timestamp, current_timestamp);

INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (3, 1, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (3, 1, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (3, 1, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (3, 1, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (3, 1, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (3, 1, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (3, 6, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (3, 6, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (3, 6, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (3, 6, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (3, 6, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (3, 6, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (3, 6, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (3, 5, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (3, 5, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (3, 5, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (3, 5, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (3, 5, 5, current_timestamp, current_timestamp);

INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (4, 1, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (4, 1, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (4, 1, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (4, 1, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (4, 1, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (4, 1, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (4, 6, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (4, 6, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (4, 6, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (4, 6, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (4, 6, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (4, 6, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (4, 6, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (4, 5, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (4, 5, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (4, 5, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (4, 5, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (4, 5, 5, current_timestamp, current_timestamp);

INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (5, 1, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (5, 1, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (5, 1, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (5, 1, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (5, 2, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (5, 2, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (5, 2, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (5, 2, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (5, 3, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (5, 3, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (5, 3, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (5, 3, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (5, 4, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (5, 4, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (5, 4, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (5, 4, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (5, 5, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (5, 5, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (5, 5, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (5, 5, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (5, 6, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (5, 6, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (5, 6, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (5, 6, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (5, 7, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (5, 7, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (5, 7, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (5, 7, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (5, 8, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (5, 8, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (5, 8, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (5, 8, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (5, 9, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (5, 9, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (5, 9, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (5, 9, 1, current_timestamp, current_timestamp);

INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (6, 1, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (6, 1, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (6, 1, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (6, 1, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (6, 2, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (6, 2, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (6, 2, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (6, 2, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (6, 3, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (6, 3, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (6, 3, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (6, 3, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (6, 4, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (6, 4, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (6, 4, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (6, 4, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (6, 5, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (6, 5, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (6, 5, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (6, 5, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (6, 6, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (6, 6, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (6, 6, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (6, 6, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (6, 7, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (6, 7, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (6, 7, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (6, 7, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (6, 8, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (6, 8, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (6, 8, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (6, 8, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (6, 9, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (6, 9, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (6, 9, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (6, 9, 2, current_timestamp, current_timestamp);

INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (7, 1, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (7, 1, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (7, 1, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (7, 1, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (7, 2, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (7, 2, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (7, 2, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (7, 2, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (7, 3, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (7, 3, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (7, 3, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (7, 3, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (7, 4, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (7, 4, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (7, 4, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (7, 4, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (7, 5, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (7, 5, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (7, 5, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (7, 5, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (7, 6, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (7, 6, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (7, 6, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (7, 6, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (7, 7, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (7, 7, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (7, 7, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (7, 7, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (7, 8, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (7, 8, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (7, 8, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (7, 8, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (7, 9, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (7, 9, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (7, 9, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (7, 9, 2, current_timestamp, current_timestamp);

INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (8, 1, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (8, 1, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (8, 1, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (8, 1, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (8, 2, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (8, 2, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (8, 2, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (8, 2, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (8, 3, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (8, 3, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (8, 3, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (8, 3, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (8, 4, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (8, 4, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (8, 4, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (8, 4, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (8, 5, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (8, 5, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (8, 5, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (8, 5, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (8, 6, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (8, 6, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (8, 6, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (8, 6, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (8, 7, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (8, 7, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (8, 7, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (8, 7, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (8, 8, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (8, 8, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (8, 8, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (8, 8, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (8, 9, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (8, 9, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (8, 9, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (8, 9, 4, current_timestamp, current_timestamp);

INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (9, 1, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (9, 1, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (9, 1, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (9, 1, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (9, 2, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (9, 2, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (9, 2, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (9, 2, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (9, 3, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (9, 3, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (9, 3, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (9, 3, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (9, 4, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (9, 4, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (9, 4, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (9, 4, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (9, 5, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (9, 5, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (9, 5, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (9, 5, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (9, 6, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (9, 6, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (9, 6, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (9, 6, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (9, 7, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (9, 7, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (9, 7, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (9, 7, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (9, 8, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (9, 8, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (9, 8, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (9, 8, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (9, 9, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (9, 9, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (9, 9, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (9, 9, 2, current_timestamp, current_timestamp);

INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (10, 1, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (10, 1, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (10, 1, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (10, 1, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (10, 2, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (10, 2, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (10, 2, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (10, 2, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (10, 3, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (10, 3, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (10, 3, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (10, 3, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (10, 4, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (10, 4, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (10, 4, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (10, 4, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (10, 5, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (10, 5, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (10, 5, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (10, 5, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (10, 6, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (10, 6, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (10, 6, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (10, 6, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (10, 7, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (10, 7, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (10, 7, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (10, 7, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (10, 8, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (10, 8, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (10, 8, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (10, 8, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (10, 9, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (10, 9, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (10, 9, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (10, 9, 2, current_timestamp, current_timestamp);

INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (11, 1, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (11, 1, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (11, 1, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (11, 1, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (11, 2, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (11, 2, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (11, 2, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (11, 2, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (11, 3, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (11, 3, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (11, 3, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (11, 3, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (11, 4, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (11, 4, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (11, 4, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (11, 4, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (11, 5, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (11, 5, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (11, 5, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (11, 5, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (11, 6, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (11, 6, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (11, 6, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (11, 6, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (11, 7, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (11, 7, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (11, 7, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (11, 7, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (11, 8, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (11, 8, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (11, 8, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (11, 8, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (11, 9, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (11, 9, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (11, 9, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (11, 9, 4, current_timestamp, current_timestamp);

INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (12, 1, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (12, 1, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (12, 1, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (12, 1, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (12, 2, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (12, 2, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (12, 2, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (12, 2, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (12, 3, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (12, 3, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (12, 3, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (12, 3, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (12, 4, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (12, 4, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (12, 4, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (12, 4, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (12, 5, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (12, 5, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (12, 5, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (12, 5, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (12, 6, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (12, 6, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (12, 6, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (12, 6, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (12, 7, 3, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (12, 7, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (12, 7, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (12, 7, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (12, 8, 5, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (12, 8, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (12, 8, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (12, 8, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (12, 9, 2, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (12, 9, 1, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (12, 9, 4, current_timestamp, current_timestamp);
INSERT INTO grade (student_id, discipline_id, grade, created_at, update_at) VALUES (12, 9, 5, current_timestamp, current_timestamp);
